### ISSUE TITLE
Unpickling errors

### ISSUE THREAD

**Issue by isspek** [RMSnow/WWW2021#12]
Hello @RMSnow,

I am receiving invalid load key errors from the pickle files. The issue persists even I created new pickles from the preprocessing.ipynb.

The error for the preprocess-lexicon.pkl is:
UnpicklingError: invalid load key, '\x00'.

And the error for the other pickle file is:
UnpicklingError: invalid load key, '\x0c'.

I would appreciate if you know the solution.

**Comment by RMSnow** [comment]
Hi @isspek, 

I suppose the issue is probably caused by the incompatible `joblib` package's version. 

If you are familiar with the `pickle` package, I suggest you try to change the `joblib` to `pickle` to save the pickle files. That means you need to update the source code of `preprocess.ipynb` (just one or two lines).  

May it can help you.
